### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [Hietan/Hietan_ZshTheme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

The plugin's repository name is very generic. Please consider renaming it to something descriptive, or even just name it `hietan.zsh-theme` after the plugin file.

Finally, don't take these as criticisms of the work you've done, they're meant to make a more useful entry in the plugin/theme list.

Thanks!

**Comment by Hietan** [comment]
Hi @unixorn 
Thanks to send issue to my repository!

I responded to the content of the issue. 
* Add screenshot image to README
* Add LICENSE file (MIT LIcense)
* Changed repository name to `Hietan_ZshTheme`

Please let me know if more tasks are needed.
I will gradually add explanations and improve the source code in order to make the repository better.

I'm not native English user, so I'm sorry if my expression is rude.

Best Regards
